<div class="alert alert-block bg-primary">
<center>MÉTODOS NUMÉRICOS</center>
<center>LISTA 06</center>
<center>ALUNA: MARIA LUÍZA TEIXEIRA NASCIMENTO</center>
</div>

In [1]:
import pandas as pd
import numpy as np
import scipy.linalg as sla
from scipy.linalg import lu_factor, lu_solve

<div class="alert alert-block alert-info">
<center><strong>Exercício 1.1:</strong> Classifique os sistemas abaixo com relação a quantidade e existência de soluções.</center>
</div>

<p> Implemente uma função que encontre o vetor solução de um sistema de equações lineares usando
decomposição LU.</p>
<p>Para testar e verificar se a função de vocês está corretamente implementada, compare os resultados com a função lu_solve da biblioteca Scipy, cujo uso também foi discutido no notebook, para os seguintes exemplos de sistemas</p>

In [2]:
def decomposicaoLU(A):
    n=len(A[0])
    L = np.zeros([n,n])
    U = np.zeros([n, n])
    for i in range(n):
        L[i][i]=1
        if i==0:
            U[0][0] = A[0][0]
            for j in range(1,n):
                U[0][j]=A[0][j]
                L[j][0]=A[j][0]/U[0][0]
        else:
            for j in range(i, n):# Para o U
                temp=0
                for k in range(0, i):
                    temp = temp+L[i][k] * U[k][j]
                U[i][j]=A[i][j]-temp
            for j in range(i+1, n):# Para o L
                temp = 0
                for k in range(0, i ):
                    temp = temp + L[j][k] * U[k][i]
                L[j][i] = (A[j][i] - temp)/U[i][i]
    return L,U

<center>Explicação do que foi feito</center>

<p>Inicializamos o $L$ e $U$ como uma matriz de zeros. Dentro do <strong>for</strong>, assumimos na diagonal principal da matriz $L$ o valor de 1. Dentro do primeiro <strong>if</strong> temos o caso para o primeiro elementro (indice zero), temos que o valor que está na matriz $A$ irá para a matriz $U$ e também temos a inserção de dados abaixo da matriz principal, calculados através de um for e 1 até o tamanho da matriz com as operação $U[0][j] = A[0][j]$ e $L[j][0] = \frac{A[j][0]}{U[0][0]}$.</p>
<p>Quando o indice for diferente de 0, temos percorremos a matriz com o <strong>for</strong> e através da operação $temp = temp + L[i][k] * U[k][j]$ e a operação $U[i][j] = A[i][j] - temp$ para a atribuição na matriz $U$.</p>
<p>Para a atribuição na matriz $L$ temos operações parecidas com a exceção da linha $L[j][i] =\frac{(A[j][i] - temp)}{U[i][i]}$</p>
<p><strong>Ao final temos o retorno do $L$ e $U$</strong> que foram calculados anteriormente.</p>

<p>Para a confirmação das respostas foi utilizado o método <strong>sla.lu_solve</strong> da biblioteca <strong>scipy.linalg</strong>.</p>

<div class="alert alert-block alert-info">
<center><strong>Letra A:</strong></center>
</div>

<p>$x_1 + x_2 + x_3 = 1$</p>
<p>$4x_1 + 4x_2 + 2x_3 = 2$</p>
<p>$2x_1 + x_2 - x_3 = 0$</p>

In [3]:
A = np.array([[1, 1, 1], [4, 4, 2], [2, 1, -1]])
B = np.array([1, 2, 0])

In [4]:
print(decomposicaoLU(A))

(array([[  1.,   0.,   0.],
       [  4.,   1.,   0.],
       [  2., -inf,   1.]]), array([[  1.,   1.,   1.],
       [  0.,   0.,  -2.],
       [  0.,   0., -inf]]))


C:\Users\Patrícia Nascimento\Anaconda3\lib\site-packages\ipykernel_launcher.py:22: RuntimeWarning: divide by zero encountered in double_scalars


<center>Solução resolvida com o <strong>sla.lu_solve</strong></center>

In [5]:
print(sla.lu_solve(sla.lu_factor(A), B))

[ 1. -1.  1.]


<div class="alert alert-block alert-info">
<center><strong>Letra B:</strong></center>
</div>

<p>$7x_1 - 7x_2 + x_3 = 1$</p>
<p>$-3x_1 + 3x_2 + 2x_3 = 2$</p>
<p>$7x_1 + 7x_2 - 72x_3 = 7$</p>

In [6]:
C = np.array([[7, -7, 1], [-3, 3, 2], [7, 7, -72]])
D = np.array([1, 2, 7])

In [7]:
print(decomposicaoLU(C))

(array([[ 1.        ,  0.        ,  0.        ],
       [-0.42857143,  1.        ,  0.        ],
       [ 1.        ,         inf,  1.        ]]), array([[ 7.        , -7.        ,  1.        ],
       [ 0.        ,  0.        ,  2.42857143],
       [ 0.        ,  0.        ,        -inf]]))


C:\Users\Patrícia Nascimento\Anaconda3\lib\site-packages\ipykernel_launcher.py:22: RuntimeWarning: divide by zero encountered in double_scalars


<center>Solução resolvida com o <strong>sla.lu_solve</strong></center>

In [8]:
print(sla.lu_solve(sla.lu_factor(C), D))

[5.64285714 5.64285714 1.        ]


<div class="alert alert-block alert-info">
<center><strong>Letra C:</strong></center>
</div>

<p>$1x_1 + 2x_2 + 3x_3 + 4x_4 = 20$</p>
<p>$2x_1 + 2x_2 + 3x_3 + 4x_4 = 22$</p>
<p>$3x_1 + 3x_2 + 3x_3 + 4x_4 = 22$</p>
<p>$4x_1 + 4x_2 + 4x_3 + 4x_4 = 24$</p>


In [9]:
E = np.array([[1, 2, 3, 4], [2, 2, 3, 4], [3, 3, 3, 4], [4, 4, 4, 4]])
F = np.array([20, 22, 22, 24])

In [10]:
print(decomposicaoLU(E))

(array([[1.        , 0.        , 0.        , 0.        ],
       [2.        , 1.        , 0.        , 0.        ],
       [3.        , 1.5       , 1.        , 0.        ],
       [4.        , 2.        , 1.33333333, 1.        ]]), array([[ 1.        ,  2.        ,  3.        ,  4.        ],
       [ 0.        , -2.        , -3.        , -4.        ],
       [ 0.        ,  0.        , -1.5       , -2.        ],
       [ 0.        ,  0.        ,  0.        , -1.33333333]]))


<center>Solução resolvida com o <strong>sla.lu_solve</strong></center>

In [11]:
print(sla.lu_solve(sla.lu_factor(E), F))

[ 2. -2.  2.  4.]
